version: "3.8"

services:
  user_api_service:
    build:
      context: ./user_api_service
    container_name: user_api_service
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=mysecret
      - DATABASE_URL=postgresql://user:password@db_user:5432/user_db
    depends_on:
      - db_user
    restart: always
    networks:
      - app_network

  file_service:
    build:
      context: ./file_storage_service
    container_name: file_service
    ports:
      - "8002:8000"
    environment:
      - SECRET_KEY=mysecret
      - USER_API_URL=http://user_api_service:8000
    depends_on:
      - user_api_service
    restart: always
    networks:
      - app_network

  db_user:
    image: postgres:14
    container_name: db_user
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  user_db_data:
